# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

pool:
  vmImage: 'macOS 10.13'

steps:

- task: Xcode@5
  inputs:
    actions: 'clean build analyze archive'
    configuration: '$(configuration)'
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    packageApp: true
    archivePath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'